### ISSUE TITLE
Chiseled sandstone issue.

### ISSUE THREAD

**Issue by alpharou** [Pokefenn/Chisel#39]
When you craft Chiseled Sandstone (The new added by Chisel) You can't use it on the chisel it must be Minecraft vanilla sandstone. I crafted the chiseled sandstone (Added by chisel) crafting sandstone scribbles in 1x1.
Chisel version: 1.5.6b for minecraft 1.7.10.
Forge version: 10.13.0.120
I made an unlisted video about the issue: http://youtu.be/dPT0kREXUDE

**Comment by EoD** [comment]
_This video is private_, maybe you want to set the video to "unlisted" next time :)

@Pokefenn  Why does Chisel has its own version of "Chiseled Sandstone"? Shouldn't the recipe of Sandstone Scrible->Chiseled Sandstone, return a vanilla Chiseled sandstone instead?

**Comment by alpharou** [comment]
Done :P

**Comment by EoD** [comment]
I found the issue and made a temporary fix in EoD/Chisel@1d11c221621a36d0855b63b7549076a4c6b61474 but there is more work required to make this a proper fix. Once I am done, I'll create a pull request.

**Comment by EoD** [comment]
The bug was introduced by b23d2b116339d95eb98bc8de56ccf51157741fad and should only appear in 1.5.6b .

I tried very many ways to replace the block, but it's all too much work. I am going to remove the block from the game and add a compatibility recipe to turn it into vanilla chiseled sandstone.
Not many people should have obtained it anyway.
